name: byteback
description: A peer-to-peer platform for buying and selling secondhand electronics to reduce e-waste.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  url_launcher: ^6.1.10
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/iphone15pro.jpg
    - assets/images/iphone15pro_2.jpg
    - assets/images/iphone15pro_3.jpg
    - assets/images/iphone14.jpg
    - assets/images/iphone13.jpg
    - assets/images/samsung.jpg
    - assets/images/ipad.jpg
    - assets/images/macbook.jpg
    - assets/images/asus.jpg
    - assets/images/acer.jpg
    - assets/images/placeholder.jpg